from pathlib import Path

provider = Path('lib/whatsapp/provider.ts')
provider.write_text('''import { createHmac, timingSafeEqual } from "node:crypto";\n\nexport function verifyWebhook(raw: string, timestamp: string | null, signature: string | null, secret = process.env.WHATSAPP_WEBHOOK_SECRET) {\n  if (!secret || secret.length < 32 || !timestamp || !signature || !/^\\d+$/.test(timestamp)) return false;\n  if (Math.abs(Date.now() - Number(timestamp)) > 5 * 60_000) return false;\n  const expected = createHmac("sha256", secret).update(`${timestamp}.${raw}`).digest("hex");\n  if (!/^[a-f0-9]{64}$/i.test(signature)) return false;\n  return timingSafeEqual(Buffer.from(expected, "hex"), Buffer.from(signature, "hex"));\n}\n''', encoding='utf-8')

Path('lib/whatsapp/worker-status.ts').write_text('''import { and, eq } from "drizzle-orm";\nimport { getDb } from "@/db";\nimport { settings } from "@/db/schema";\n\nconst STATUS_KEY = "jj_whatsapp_worker_status";\nconst HEARTBEAT_MAX_AGE_MS = 75_000;\n\ntype WorkerStatus = { connected?: boolean; phone?: string; qr?: string; workerId?: string; version?: string; updatedAt?: string };\n\nexport async function getBridgeStatus(workspaceId: string) {\n  const [row] = await getDb().select({ value: settings.value, updatedAt: settings.updatedAt }).from(settings).where(and(eq(settings.workspaceId, workspaceId), eq(settings.key, STATUS_KEY))).limit(1);\n  if (!row) return { configured: false, connected: false, message: "WhatsApp-Laptop noch nicht eingerichtet", phone: "", qr: "" };\n  let value: WorkerStatus = {};\n  try { value = JSON.parse(row.value) as WorkerStatus; } catch { /* malformed status is offline */ }\n  const stamp = Date.parse(value.updatedAt || row.updatedAt.toISOString());\n  const fresh = Number.isFinite(stamp) && Date.now() - stamp < HEARTBEAT_MAX_AGE_MS;\n  const connected = fresh && value.connected === true;\n  return { configured: true, connected, phone: value.phone || "", qr: fresh && typeof value.qr === "string" ? value.qr : "", message: connected ? "WhatsApp über den lokalen Laptop verbunden" : fresh && value.qr ? "QR-Code mit WhatsApp scannen" : "WhatsApp-Laptop starten" };\n}\n''', encoding='utf-8')

route = Path('app/api/whatsapp/route.ts')
text = route.read_text(encoding='utf-8')
text = text.replace('import { getBridgeStatus } from "@/lib/whatsapp/provider";', 'import { getBridgeStatus } from "@/lib/whatsapp/worker-status";')
route.write_text(text, encoding='utf-8')
print('Provider test isolation fixed.')
